# Generated by Django 4.2.20 on 2025-04-10 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_country_module', '0001_initial'),
        ('businessdetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='businessdetail',
            old_name='company_name',
            new_name='business_name',
        ),
        migrations.RenameField(
            model_name='businessdetail',
            old_name='address',
            new_name='website',
        ),
        migrations.RemoveField(
            model_name='businessdetail',
            name='business_category',
        ),
        migrations.RemoveField(
            model_name='businessdetail',
            name='email',
        ),
        migrations.RemoveField(
            model_name='businessdetail',
            name='pan',
        ),
        migrations.AddField(
            model_name='businessdetail',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common_country_module.country'),
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='gstin',
            field=models.EmailField(max_length=254),
        ),
        migrations.AddField(
            model_name='businessdetail',
            name='team_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='businessdetails.teamsize'),
        ),
    ]
