# Generated by Django 4.2.20 on 2025-04-14 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('businessdetails', '0002_teamsize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetail',
            name='gstin',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
