# Generated by Django 4.2.20 on 2025-04-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessdetails', '0003_alter_businessdetail_gstin_alter_businessdetail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetail',
            name='phone',
            field=models.CharField(max_length=25),
        ),
    ]
