# Generated by Django 4.2.20 on 2025-04-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessdetails', '0004_alter_businessdetail_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetail',
            name='gstin',
            field=models.CharField(max_length=25),
        ),
    ]
