# Generated by Django 4.2.20 on 2025-04-15 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('businessdetails', '0005_alter_businessdetail_gstin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
