# Generated by Django 4.2.20 on 2025-04-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessdetails', '0006_alter_businessdetail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetail',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='businessdetail',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='businessdetail',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='business/logos/'),
        ),
        migrations.AddField(
            model_name='businessdetail',
            name='postal_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='businessdetail',
            name='state',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='businessdetail',
            name='street_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessdetail',
            name='tax',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
