# Generated by Django 4.2.20 on 2025-04-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessdetails', '0007_businessdetail_city_businessdetail_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetail',
            name='email',
            field=models.EmailField(default='unknown', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='businessdetail',
            name='postal_code',
            field=models.CharField(default='unknown', max_length=15),
        ),
    ]
