# Generated by Django 4.2.20 on 2025-04-29 05:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('businessdetails', '0009_alter_businessdetail_city_alter_businessdetail_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teamsize',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamsize',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
