# Generated by Django 4.2.20 on 2025-05-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessdetails', '0010_businessdetail_created_at_businessdetail_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetail',
            name='gstin',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
