# Generated by Django 4.2.20 on 2025-05-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date_timestamp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date_timestamp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
