# Generated by Django 4.2.20 on 2025-05-12 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_country_module', '0001_initial'),
        ('projects', '0003_project_adminpanel_project_android_project_document1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common_country_module.country'),
            preserve_default=False,
        ),
    ]
