# Generated by Django 4.2.20 on 2025-05-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='country',
            new_name='country_id',
        ),
        migrations.AlterField(
            model_name='project',
            name='adminPanel',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='android',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='document1',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='document2',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='iosApp',
            field=models.CharField(blank=True, null=True),
        ),
    ]
