# Generated by Django 4.2.20 on 2025-05-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_adminpanel_alter_project_android_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='adminPanel',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='project',
            name='android',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='project',
            name='developer_name',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='project',
            name='document1',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='project',
            name='document2',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='project',
            name='iosApp',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='project',
            name='repo_link',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='project',
            name='website',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
