# Generated by Django 4.2.20 on 2025-05-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_adminpanel_alter_project_android_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='adminPanel',
        ),
        migrations.RemoveField(
            model_name='project',
            name='android',
        ),
        migrations.RemoveField(
            model_name='project',
            name='document1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='document2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='iosApp',
        ),
        migrations.RemoveField(
            model_name='project',
            name='website',
        ),
        migrations.AddField(
            model_name='project',
            name='documents',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='live_links',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='project',
            name='repo_link',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
