# Generated by Django 4.2.20 on 2025-05-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_project_adminpanel_remove_project_android_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='repo_link',
            new_name='repo_links',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_technology',
            field=models.JSONField(default=list),
        ),
    ]
