# Generated by Django 4.2.20 on 2025-04-14 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common_country_module', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='address',
            new_name='Pan',
        ),
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='business_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='city_town',
            field=models.CharField(default='Unknown', max_length=150),
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(default='Unknown', max_length=150),
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common_country_module.country'),
        ),
        migrations.AddField(
            model_name='client',
            name='gstin',
            field=models.CharField(default='Unknown', max_length=15),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
