# Generated by Django 4.2.20 on 2025-04-14 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_rename_address_client_pan_remove_client_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='Pan',
            new_name='pan',
        ),
    ]
