# Generated by Django 4.2.20 on 2025-04-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_rename_pan_client_pan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='business_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='city_town',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='client',
            name='gstin',
            field=models.CharField(max_length=15),
        ),
    ]
