# Generated by Django 4.2.20 on 2025-04-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_business_name_alter_client_city_town_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='city_town',
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='street_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
