# Generated by Django 4.2.20 on 2025-04-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_client_city_town_client_city_client_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='postal_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
