# Generated by Django 4.2.20 on 2025-04-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='postal_code',
            field=models.CharField(default='unknown', max_length=15),
        ),
    ]
