# Generated by Django 4.2.20 on 2025-04-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_client_city_alter_client_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='postal_code',
            field=models.CharField(max_length=15),
        ),
    ]
