# Generated by Django 4.2.20 on 2025-04-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_client_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_region',
            field=models.CharField(default='Unknown', max_length=15),
        ),
    ]
