# Generated by Django 4.2.20 on 2025-05-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_client_created_at_client_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
