# Generated by Django 4.2.20 on 2025-04-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='salesuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='salesuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='salesuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='salesuser',
            name='username',
        ),
        migrations.AddField(
            model_name='salesuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='salesuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='salesuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salesuser',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
