# Generated by Django 4.2.20 on 2025-04-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_salesuser_category_salesuser_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesuser',
            name='address',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AlterField(
            model_name='salesuser',
            name='phone',
            field=models.CharField(default='Unknown', max_length=15),
        ),
    ]
