# Generated by Django 4.2.20 on 2025-04-29 05:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_salesuser_address_alter_salesuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
