# Generated by Django 4.2.20 on 2025-04-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_invoice_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_logo',
            field=models.ImageField(default='unknown', upload_to='invoices/logos/'),
        ),
    ]
