# Generated by Django 4.2.20 on 2025-04-29 05:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_invoice_invoice_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
