# Generated by Django 4.2.20 on 2025-05-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_invoiceitem_created_at_invoiceitem_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
