# Generated by Django 4.2.20 on 2025-05-07 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankdetails', '0004_bankdetail_created_at_bankdetail_updated_at'),
        ('invoice', '0005_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bankdetails.bankdetail'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(default='draft', max_length=100),
        ),
    ]
