# Generated by Django 4.2.20 on 2025-05-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_invoice_bank_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_logo',
            field=models.FileField(blank=True, default='unknown', null=True, upload_to='invoice_logos/'),
        ),
    ]
